services:

  app:
    build: ./app
    container_name: front-end 
    volumes: ['./app/src:/appcode']
      #    restart: unless-stopped
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ['./api:/apicode']
      
    ports:
      - 4000:4000

  db:
    env_file:
      - ./doc-fly-db/.env
    build: ./dbfiles
    container_name: doc-fly-db

    ports:
      - 3306:3306

    restart: unless-stopped


