# fly.toml app configuration file generated for doc-fly-db on 2024-06-08T14:35:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doc-fly-db'
primary_region = 'ams'

[build]

[env]
  MYSQL_USER = 'web_app_user'

[processes]
  app = '--datadir /data/mysql --mysql_native_password=ON'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
