# fly.toml app configuration file generated for doc-fly-api on 2024-06-08T14:47:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doc-fly-api'
primary_region = 'ams'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
